# Generated by Django 2.0 on 2019-08-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190812_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
